public enum Keybinding {
    HORIZONTAL, VERTICAL, JUMP,
    MOUSE_X, MOUSE_Y, MOUSE_SCROLL_WHEEL, LOOK_BACK,
    FIRE1, FIRE2, FIRE3, FIRE4, CHANGE_WEAPON,
    TOGGLE_CHAT_VISIBILTY, TOGGLE_HUD_VISIBILTY, SUBMIT, CANCEL, SUICIDE,
    NONE
}
